### ISSUE TITLE
Update Project mutation bug

### ISSUE THREAD

**Issue by divyareddynu** [nulib/meadow#1683]
### Description
I tried to update project by sending projectId and projectTitle but it is creating a new project instead of updating the existing one.
Here's the graphQL I followed:
```
mutation UpdateProject($projectId: ID!, $projectTitle: String!) {
    updateProject(id: $projectId, title: $projectTitle) {
      id
      title
      folder
    updatedAt
    }
  }
```

### Done looks like
- [ ] `updateProject` mutation successfully updates an existing project.

**Comment by kdid** [comment]
closing. wrong repo. opened https://github.com/nulib/repodev_planning_and_docs/issues/1429

**Comment by divyareddynu** [comment]
@kdid We can use `Transfer issue` to move it to a different repo
<img width="464" alt="Screen Shot 2021-01-13 at 9 36 53 AM" src="https://user-images.githubusercontent.com/72217877/104473807-fcc7e400-5582-11eb-963d-8b080b6cedbf.png">
