### ISSUE TITLE
Filtering bug in Collections Routing

### ISSUE THREAD

**Issue by mbklein** [nulib/meadow#371]
Filtering works until something gets filtered out, but then it won't come back unless you reset the whole filter.

![collection_filter](https://user-images.githubusercontent.com/196872/70745054-a7b70000-1ce8-11ea-976e-98e763b2aa85.gif)

**Comment by adamjarling** [comment]
@mbklein Thanks for the find.  It's just doing a basic string match against the Collection name for now, until we figure out where this data will live (Elasticsearch?), but will refine it a bit more now.
