### ISSUE TITLE
Clean up UIProgressBar

### ISSUE THREAD

**Issue by katdivyareddy10** [nulib/meadow#530]
### Description
UIProgressBar to match current theme and eliminate any errors related to progress bar.

### Done looks like
- UIProgressBar matches our theme
- UIProgressBar props are set to "number" type for percentComplete.

![Screen Shot 2020-02-21 at 1.52.01 PM.png](https://images.zenhubusercontent.com/5e43103ed7d2429d18f93c92/31da0929-76ff-4062-a86c-4b88b78aadbf)
![Screen Shot 2020-02-21 at 1.58.33 PM.png](https://images.zenhubusercontent.com/5e43103ed7d2429d18f93c92/4a1c9cc3-a938-4057-9732-615b4766b5a3)

**Comment by adamjarling** [comment]
I updated the color of the Progress Bar in a current PR...forgot that was in this issue:)
