### ISSUE TITLE
Validate required fields on backend if work published=true

### ISSUE THREAD

**Issue by kdid** [nulib/meadow#983]
### Description

When works come in through ingest they do not have any metadata and it is not required until the time that works are published - using the "Publish/Unpublish" toggle button in the UI. 

The spreadsheet lists required fields for descriptive and administrative metadata: https://docs.google.com/spreadsheets/d/1PBvp9FJAvG6JIP6RZwmiZSDhgYLQ6VRSknUnkodEH8Q/edit#gid=396400352

Additionally, works must belong to a collection to be published. 

### Done Looks Like
- [ ] Update backend for updateWork mutation so that existence of metadata for required fields is checked and validated before the work is set to a "Published" state.

**Comment by davidschober** [comment]
One thought here: how do we deal with a batch flip to published if some validate and some don't? I'm wondering if "publish" is a separate operation from normal batch UI edit so that we can throw errors in a different way.

**Comment by kdid** [comment]
True. This issue is really about the GraphQL API and the publish work toggle button in the UI. 
I think batch publish should be a separate issue.

**Comment by davidschober** [comment]
Sounds good. I'll stub a ticket, but it's not really a fully formed thought yet.

**Comment by kdid** [comment]
closing. we decided not to validate on publish.
